name: actions
<<<<<<< HEAD
on: [push, workflow_dispatch]
=======
on: push
>>>>>>> 3587e6b00286fd2a6ca50ba616ee18fd148499c4
jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint --if-present

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test --if-present

  build:
<<<<<<< HEAD
    needs: test
=======
>>>>>>> 3587e6b00286fd2a6ca50ba616ee18fd148499c4
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build --if-present

  deploy:
<<<<<<< HEAD
    needs: build
=======
>>>>>>> 3587e6b00286fd2a6ca50ba616ee18fd148499c4
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Deploy
        run: echo "Deploying..."
