name: Deployment
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint --if-present
      - name: Test
        run: npm run test --if-present
      - name: Build
        run: npm run build --if-present
      - name: Deploy
        run: echo "Deploying..."
